import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } });
await page.goto('http://localhost:5174', { waitUntil: 'networkidle' });
await page.waitForTimeout(800);
const gh = page.getByText('GitHub', { exact: true });
await page.screenshot({ path: 'scratch_hero_before.png', clip: { x: 0, y: 0, width: 800, height: 500 } });
await gh.hover();
await page.waitForTimeout(300);
await page.screenshot({ path: 'scratch_hero_hover.png', clip: { x: 0, y: 0, width: 800, height: 500 } });
await browser.close();
